services:
  web:
    image: nginx
    ports:
      - "80:80"
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ./src:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/login.sql:/docker-entrypoint-initdb.d/login.sql
      - ./docker/mysql/posts.sql:/docker-entrypoint-initdb.d/posts.sql
      - ./docker/mysql/user.sql:/docker-entrypoint-initdb.d/user.sql
      - ./docker/mysql/post.sql:/docker-entrypoint-initdb.d/post.sql
      - ./docker/mysql/user.sql:/docker-entrypoint-initdb.d/user.sql
      - ./docker/mysql/poster.sql:/docker-entrypoint-initdb.d/poster.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci

volumes:
  db_data:
